### ISSUE TITLE
PHP error when using the cronjob URL

### ISSUE THREAD

**Issue by TehPeGaSuS** [k4bek4be/Stikked#1]
According to [this option](https://github.com/k4bek4be/Stikked/blob/k4be%2Bphp8/htdocs/application/config/stikked.php.dist#L109-L113), we need a key to execute the cronjob (probably for paste deletion?), but when visiting `https://sub.domain.tld/cron/[key]` I got the following error:

![cronjob_stikked_error](https://github.com/k4bek4be/Stikked/assets/25697531/d5ac04c6-ea94-450f-b28b-afa1f11c1a6e)

PHP version: PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)
Apache version: Apache/2.4.52 (Ubuntu)
SQLite version: 3.37.2 2022-01-06 13:25:41

**Comment by k4bek4be** [comment]
done in https://github.com/k4bek4be/Stikked/commit/3d885eaa50a1ed7d179124fa08925c295b9940ae
